import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useGameStore } from "../store/game";
export function RecentWinners() {
    const history = useGameStore((s) => s.winnersHistory);
    return (_jsxs("div", { className: "rounded-2xl bg-black/30 p-2 shadow border border-white/10 h-full flex flex-col", children: [_jsxs("div", { className: "flex items-center justify-between mb-2 flex-shrink-0", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-sm", children: "\uD83C\uDF89" }), _jsx("h3", { className: "text-white font-bold text-xs", children: "Recent Winners" })] }), _jsx("span", { className: "text-xs text-purple-400 bg-purple-400/20 px-1 py-0.5 rounded-full", children: "Latest" })] }), _jsxs("div", { className: "flex-1 overflow-y-auto scrollbar-hide space-y-1", children: [history.length === 0 && (_jsxs("div", { className: "text-center py-2 text-white/60", children: [_jsx("div", { className: "text-lg mb-1", children: "\uD83C\uDFC5" }), _jsx("div", { className: "text-xs", children: "No winners yet" })] })), (history || []).slice(-2).reverse().map((h) => (_jsxs("div", { className: "p-1.5 rounded-lg bg-white/5 border border-white/10", children: [_jsxs("div", { className: "flex items-center justify-between mb-1", children: [_jsxs("span", { className: "text-white/70 text-xs font-mono", children: ["Round #", h.roundId] }), _jsx("span", { className: "text-green-400 text-xs", children: "\u2713" })] }), _jsxs("div", { className: "space-y-0.5", children: [(h.winners || []).slice(0, 2).map((w, idx) => (_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { className: "text-xs", children: idx === 0 ? "🥇" : "🥈" }), _jsx("span", { className: "text-white/90 text-xs font-mono", children: short(w.name || w.id) })] }), _jsxs("div", { className: "flex items-center gap-1 text-xs", children: [w.score && (_jsx("span", { className: "text-green-400", children: w.score })), w.latencySec && (_jsxs("span", { className: "text-blue-400", children: [w.latencySec.toFixed(1), "s"] }))] })] }, w.id))), h.winners.length > 2 && (_jsxs("div", { className: "text-white/50 text-xs text-center", children: ["+", h.winners.length - 2, " more"] }))] })] }, h.roundId)))] })] }));
}
function short(s) {
    if (!s)
        return 'Unknown';
    return s.length > 10 ? `${s.slice(0, 4)}…${s.slice(-4)}` : s;
}
